name: Bug report
description: Report a bug
labels: ["bug"]
body:
- type: textarea
  attributes:
    label: Description
    description: |
      Describe the bug, give us as much details as you can.
  validations:
    required: true
    
- type: textarea
  attributes:
    label: Steps to reproduce
    description: |
       How to reproduce the bug. Example: click on... press.. then go to... and then...
  validations:
    required: true
    
- type: input
  attributes:
    label: Godot Engine version
    description: |
      Specify the version of your Godot Engine.
  validations:
    required: true
