name: Bug report
description: Report a bug
labels: ["bug"]
body:
- type: textarea
  attributes:
    label: Description
    description: |
      Describe the bug, give us as much details as you can.
  validations:
    required: true
    
- type: textarea
  attributes:
    label: Steps to reproduce
    description: |
       How to reproduce the bug. Example: click on... press.. then go to... and then...
  validations:
    required: true
   
   - type: textarea
  attributes:
    label: Expected behaviour
  
- type: input
  attributes:
    label: Godot Engine version
    description: |
      Specify the version of your Godot Engine.
  validations:
    required: true

- type: textarea
  attributes:
    label: Logs
    description: |
       If there's an error, it should appear in `Output'. If you're not printing Godot's logs into a file, paste the full output here. If you are printing them to a file, upload it.
  validations:
    required: true
